openshift/sprint_tools

trello

The old algorithm was:
- Remove all the cards links from the epics
- Go across all the boards and add each referencing card to it's corresponding epic as you find it
This had 2 problems:  
1) If we hit an error half way through the list it would leave a lot of epics without all their cards
2) There could be a long time period between when cards are removed from the epics and when they are readded
The new algorithm is:
- Find all the cards across all the boards that map to epics and remember them by epic
- For 1 epic at a time, remove the current card links and readd all the new links
So now the worst case for problem 1 is 1 epic might not have all its corresponding cards.  And the worst case for problem 2 is only a few seconds of the corresponding cards missing.

Restructure algorithm to minimize downtime of epic lists

---

config/trello.yml
lib/trello_helper.rb
trello

I've tested this for cases where the board doesn't exist.  For example the OpenShift board doesn't have a "top 5 priorities" board.  The script behaves as you would expect it to.

Added support for additional epic backlog boards

---

templates/labels_overview.erb

@danmcp - tell me if I followed the logic of your changes and made the change I needed to. My intent is to give the performance team the ability to label cards they are working on (on the many boards they work across) and have a list generated. I will also add a "perf" label to the appropriate place in trello.

Adding a new perf label to this report

---

lib/trello_helper.rb
trello

This change adds a method that tries to toggle a checklist item
according to the parameters supplied. It should:
* if needed, add a new checklist item with the desired state
* if needed, remove the existing checklist item that's being toggled
* verify that both of the above steps have succeeded
* recover from a failure at any of the above steps

Add retry logic to checklist updates

---

lib/trello_helper.rb
trello

Adds `backup_org_boards` which takes `--output-dir` argument. Iterates over all boards in the organization and dumps the JSON export to `<output-dir>/<board-name>.json`, or `$PWD/<board-name.json>` if no `--output-dir` is specified.

Iterate over all boards and back them up

---

lib/trello_helper.rb

Added the alternate request parameters as a map instead of including in
the URL
more verbose, but more clean

clean up dump_board_json

---

lib/trello_helper.rb

The `Trello::Card` object stores the card label data in a hash, which is
now being used to instantiate the `Trello::Label` objects instead of
`card.labels`, which triggers an extra API call.

Get card labels from card object, not API

---

lib/trello_helper.rb

`ruby-trello` gem version 1.5.1 includes a change to the data structure
returned by `card.labels`. This change accounts for that and fixes https://github.com/openshift/sprint_tools/issues/48

trello_helper.rb: update card_labels for new gem

---

lib/bugzilla_helper.rb

Modifies `BugzillaHelper` to process the response from `Bugzilla::Bug#search` as a Hash instead of a List of Lists of Lists.

Use bugzilla search results in a sane manner

---

README.md
config/trello.yml
lib/trello_helper.rb
trello

Organize Trello cards according to their release labels. This affects
the Next and Backlog lists on team boards. Cards will be ordered within
each product, according to release state (committed, targeted, proposed)
and release number (e.g. 3.4, 7.3.2, etc.)

Sort release cards

---

config/trello.yml
lib/trello_helper.rb
trello

Adds the capability to specify a documentation board in the config on a
global and per-team basis. Impacts `trello update --add-doc-cards`.

Add per-team documentation boards

---

README.md
config/trello.yml
lib/trello_helper.rb
templates/labels_overview.erb
trello

Generalize "docs" commands to be "dependent work"
Refactor update tasks into discrete methods
Moved update tasks into `TrelloHelper` class
Updated the config format to allow defining multiple labels that work similar to the "documentation" label. This includes multiple global labels and team-specific variants.
Renamed a bunch of `something-doc*-something` to reflect the general term `dependent-work`
Abstracted some ad-hoc collections into instance members
Updated `README.md` and doc comments

Generalize "docs" commands to be "dependent work"

---

lib/trello_helper.rb
trello

We're adding labels that look like "`committed-online-fy18.q2`", so `TrelloHelper::RELEASE_LABEL_REGEX` and `TrelloHelper#sortable_card_label` need to be updated to parse and sort cards with these new style labels.
Also adds convenience functions for messing around with roadmap labels.

Tweaks to handle new labels, convenience functions for adding/listing roadmap labels

---

lib/trello_helper.rb
templates/developers_overview.erb
templates/releases_overview.erb
templates/sprint_schedule.erb
templates/teams_overview.erb
trello

These changes:
* fix a regex to extract version numbers from our `-fy18.q3` style
labels for sorting
* also support any non-digit prefix for the version/release number
parts, e.g. `-fy18.q3.r2.4`
* drop some of the captured groups so that we only pull out the parts
of the label that we're using
* update dependent code to use `.match` and to reference the capture
groups in the result according to the changes mentioned above
Sometimes you need an ASCII diagram to understand a regex :/

Rewrite RELEASE_LABEL_REGEX code to use .match, tweak regex

---

lib/trello_helper.rb
trello

Takes the modulus of the days left in sprint against 21 (3 weeks) so
the output is correct even if the sprint card has been updated prior
to end of sprint.

Fixup trello days_left_in_sprint

---

.travis.yml
README.md
Rakefile
lib/overviews_helper.rb
lib/trello_helper.rb
templates/developers_overview.erb
templates/releases_overview.erb
templates/teams_overview.erb
test/files/std_config.yml
test/helper.rb
test/test_overviews_helper.rb
test/test_trello_helper.rb
trello

`generate_raw_overview` generates CSV export for all overview content
Adds `overviews_helper.rb` to partition logic; unclutters `trello` script
and consolidates a lot of related functionality.
Adds tests for new raw overview methods
Cleans up warnings from `rake test`
Update `README.md` and polish some of the `--help` output

Implement CSV export and initial unit tests

---

lib/trello_helper.rb

Added `!!` idiom to ensure values generated by new
`list_for_completed_work?` and `list_for_in_progress_work?` methods is
`true|false`, since the `Trello::Checklist#add_item` method requires
an actual boolean for `checked` state.

Fix checklist_add_item call

---

.gitignore
Gemfile
lib/trello_helper.rb
lib/trello_json_loader.rb
test/helper.rb
test/test_overviews_helper.rb
test/test_trello_helper.rb
test/test_trello_helper_add_methods.rb
trello

This change was started to add JSON backup loading, so overview pages,
reports, etc. could be generated from backed up content without having
to query the API at all. This also will help make it easier to add unit
tests, new functionality like templated Trello object primitives - e.g. to
simplify creating new boards - etc.
Implementing the JSON loader exposed some problems with the Org boards
backup functionality which is also fixed in this change. Additionally,
backing up at the Org level is now supported, as is backing up the
current Org members list.
New methods for consistently adding new objects to the TrelloHelper
cache vars have been added, `add_card`, `add_label`, etc.
Tests for some of these things have been added, but to make concurrent
changes easier, the remainder of the tests …

Adds json loader, backup for org and org members

---

lib/trello_helper.rb
test/files/no_dependent_work_boards_config.yml
test/helper.rb
test/test_trello_helper.rb
trello

Fix exceptions when no dependent work boards are defined.
Also uses `members_by_id` caching method to get member data for `trello list` instead of pounding the `/1/members/` API endpoint, which invariably trips the rate limiter. Using the caching method incidentally adds retry logic as well, so it shouldn't bail out so easily now.

fix dependent work board logic, optimize `trello list`

---

config/trello.yml

Added example:
:current_release_labels:
- committed-1.0
- targeted-1.0
:next_release_labels:
- committed-1.1
- targeted-1.1

Add release label examples to trello.yml config file

---

lib/ldap_helper.rb

Each `ldap` helper function started with `ldap.bind do ...`. By only
binding once, `trello list_invalid_users` is at least 3x faster.
derp

Stop binding LDAP on every single query
